{
 "title": "Heizung",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Betriebsart",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Betriebsart HK1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: -1d, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HK1_BW1_Automatik\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"status\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Betriebsart WW",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: -1mo, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WW_BW1_Automatik\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"status\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Tag/Nacht",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: -1d, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HK1_BW2_Tag\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"status\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Sommer/Winter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: -1d, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HK1_BW2_Sommer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"status\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Brenneransteuerung",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: -1d, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Brenner_Ansteuerung\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"status\")\n  |> last()"
    }
   ]
  },
  {
   "title": "HK1 Pumpe",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: -7d, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HK1_Pumpe\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"status\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Absenkungsart",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: -10y, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HK1_Absenkungsart\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"config\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Sommer ab",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: -12y, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sommer_ab\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"config\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Frost ab",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: -12y, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Frost_ab\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"config\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Ölzählerstand",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: -1mo, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Oelzaehler\")\n  |> last()\n  |> drop(columns: [\"_measurement\", \"_stop\", \"sensor\", \"_field\", \"ort\", \"type\"])\n  |> group()\n  |> map(fn: (r) => ({\n    r with\n    _liter: float(v: r._value/100.0),\n  }))"
    }
   ]
  },
  {
   "title": "Verbrauch seit Tanken",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: 2022-10-25T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Oelzaehler\")\n  |> last()\n  |> drop(columns: [\"_measurement\", \"_stop\", \"sensor\", \"_field\", \"ort\", \"type\"])\n  |> group()\n  |> map(fn: (r) => ({\n    r with\n    _liter: float(v: r._value/100.0),\n  }))"
    }
   ]
  },
  {
   "title": "Ölverbrauch (Auswahl)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Oelzaehler\")\n  |> spread()\n  |> drop(columns: [\"_measurement\", \"_stop\", \"sensor\", \"_field\", \"ort\", \"type\"])\n  |> group()\n  |> map(fn: (r) => ({\n    r with\n    _liter: float(v: r._value/100.0),\n  }))"
    }
   ]
  },
  {
   "title": "Laufzeit (Auswahl)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Brenner_Laufzeit_Summe\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"status\")\n  |> spread()"
    }
   ]
  },
  {
   "title": "Stromverb. (Auswahl)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"energie\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"heizung\")\n  |> filter(fn: (r) => r[\"_field\"] == \"verbrauch\")\n  |> spread()"
    }
   ]
  },
  {
   "title": "Umschaltzeiten",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tag/Nacht",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 18, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HK1_BW2_Tag\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"status\")"
    }
   ]
  },
  {
   "title": "Tag > Nacht",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 10 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/monitor\"\n\nfrom(bucket: \"heizung\")\n  |> range(start: -12mo, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HK1_BW2_Tag\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"status\")\n  |> map(fn: (r) => ({ r with _level: if r._value==0 then \"Nacht\" else \"Tag\"}))\n \n  |> monitor.stateChanges(\n      fromLevel: \"Tag\",\n      toLevel: \"Nacht\",\n  )\n\n  |> last()"
    }
   ]
  },
  {
   "title": "Nacht > Tag",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 10 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/monitor\"\n\nfrom(bucket: \"heizung\")\n  |> range(start: -12mo, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HK1_BW2_Tag\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"status\")\n  |> map(fn: (r) => ({ r with _level: if r._value==0 then \"Nacht\" else \"Tag\"}))\n \n  |> monitor.stateChanges(\n      fromLevel: \"Nacht\",\n      toLevel: \"Tag\",\n  )\n\n  |> last()"
    }
   ]
  },
  {
   "title": "Sommer/Winter",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 18, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HK1_BW2_Sommer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"status\")"
    }
   ]
  },
  {
   "title": "Sommer > Winter",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 13 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/monitor\"\n\nfrom(bucket: \"heizung\")\n  |> range(start: -12mo, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HK1_BW2_Sommer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"status\")\n  |> map(fn: (r) => ({ r with _level: if r._value==0 then \"Winter\" else \"Sommer\"}))\n \n  |> monitor.stateChanges(\n      fromLevel: \"Sommer\",\n      toLevel: \"Winter\",\n  )\n\n  |> last()"
    }
   ]
  },
  {
   "title": "Winter > Sommer",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 13 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/monitor\"\n\nfrom(bucket: \"heizung\")\n  |> range(start: -12mo, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HK1_BW2_Sommer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"status\")\n  |> map(fn: (r) => ({ r with _level: if r._value==0 then \"Winter\" else \"Sommer\"}))\n \n  |> monitor.stateChanges(\n      fromLevel: \"Winter\",\n      toLevel: \"Sommer\",\n  )\n\n  |> last()"
    }
   ]
  },
  {
   "title": "Vorlauf und Brenner",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Vorlauftemperatur",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HK1_Vorlaufsolltemperatur\" or r[\"_measurement\"] == \"HK1_Vorlaufisttemperatur\" or r[\"_measurement\"] == \"Brenner_Ansteuerung\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"status\")\n  |> aggregateWindow(every: 2m, fn: mean)"
    }
   ]
  },
  {
   "title": "Brenneransteuerung",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Brenner_Ansteuerung\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"status\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Vorlauf - SOLL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: -1y, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HK1_Vorlaufsolltemperatur\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"status\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Vorlauf - IST",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: -1d, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HK1_Vorlaufisttemperatur\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"status\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Umwälzpumpe",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "HK1 Pumpe",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HK1_Pumpe\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"status\")\n"
    }
   ]
  },
  {
   "title": "HK1 Pumpe",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: -1y, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HK1_Pumpe\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"status\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Warmwasser",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Warmwasser",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WW_Solltemperatur\" or r[\"_measurement\"] == \"WW_Isttemperatur\" or r[\"_measurement\"] == \"HK1_BW1_Warmwasservorrang\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"status\")\n  |> aggregateWindow(every: 5m, fn: mean)"
    }
   ]
  },
  {
   "title": "Warmwasser Soll",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: -1d, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WW_Solltemperatur\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"status\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Warmwasser Ist",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: -1d, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WW_Isttemperatur\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"status\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Laufzeit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Laufzeit Tage",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: -21d, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Brenner_Laufzeit_Summe\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> window(every: 1d)\n  |> spread()\n  |> drop(columns: [\"_measurement\", \"_stop\", \"sensor\", \"_field\", \"ort\", \"type\"])\n  |> group()\n"
    }
   ]
  },
  {
   "title": "Laufzeit Monate",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: -12mo, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Brenner_Laufzeit_Summe\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> window(every: 1mo)\n  |> spread()\n  |> drop(columns: [\"_measurement\", \"_stop\", \"sensor\", \"_field\", \"ort\", \"type\"])\n  |> group()\n"
    }
   ]
  },
  {
   "title": "Ölverbrauch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ölzähler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"Oelzaehler\"\n  )"
    }
   ]
  },
  {
   "title": "Füllstand",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: 2022-10-25T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Oelzaehler\")\n  |> last()\n  |> drop(columns: [\"_measurement\", \"_stop\", \"sensor\", \"_field\", \"ort\", \"type\"])\n  |> group()"
    }
   ]
  },
  {
   "title": "Ölverbrauch Tage",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: -21d, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Oelzaehler\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> window(every: 1d)\n  |> spread()\n  |> drop(columns: [\"_measurement\", \"_stop\", \"sensor\", \"_field\", \"ort\", \"type\"])\n  |> group()\n  |> map(fn: (r) => ({\n    r with\n    _liter: float(v: r._value/100.0),\n  }))\n"
    }
   ]
  },
  {
   "title": "Ölverbrauch  Monate",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: -12mo, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Oelzaehler\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> window(every: 1mo)\n  |> spread()\n  |> drop(columns: [\"_measurement\", \"_stop\", \"sensor\", \"_field\", \"ort\", \"type\"])\n  |> group()\n  |> map(fn: (r) => ({\n    r with\n    _liter: float(v: r._value/100.0),\n  }))\n"
    }
   ]
  },
  {
   "title": "Stromverbrauch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Stromverbrauch Tage",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"energie\")\n  |> range(start: -21d, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"heizung\")\n  |> filter(fn: (r) => r[\"_field\"] == \"verbrauch\")\n  |> window(every: 1d)\n  |> spread()\n  |> drop(columns: [\"_measurement\", \"_stop\", \"sensor\", \"_field\", \"ort\", \"type\"])\n  |> group()\n"
    }
   ]
  },
  {
   "title": "Stromverbrauch  Monate",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"energie\")\n  |> range(start: -12mo, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"heizung\")\n  |> filter(fn: (r) => r[\"_field\"] == \"verbrauch\")\n  |> window(every: 1mo)\n  |> spread()\n  |> drop(columns: [\"_measurement\", \"_stop\", \"sensor\", \"_field\", \"ort\", \"type\"])\n  |> group()\n"
    }
   ]
  },
  {
   "title": "Außentemperatur",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Außentemperatur",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Aussentemperatur\" or r[\"_measurement\"] == \"Aussentemperatur_gedaempft\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"status\")\n  |> aggregateWindow(every: 10m, fn: mean)"
    }
   ]
  },
  {
   "title": "Außentemperatur",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: -1d, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Aussentemperatur\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"status\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Maximum",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Aussentemperatur\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"status\")\n  |> max()"
    }
   ]
  },
  {
   "title": "Minimum",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Aussentemperatur\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"status\")\n  |> min()"
    }
   ]
  },
  {
   "title": "Debug",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 },
   "targets": [
    {}
   ]
  },
  {
   "title": "KM271",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 111 },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"type\"] == \"status\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n\n  "
    }
   ]
  },
  {
   "title": "Config Werte",
   "type": "table",
   "gridPos": { "h": 16, "w": 13, "x": 0, "y": 124 },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: -12mo, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"type\"] == \"config\")\n  |> last()\n\n  \n"
    }
   ]
  },
  {
   "title": "Status Werte",
   "type": "table",
   "gridPos": { "h": 16, "w": 11, "x": 13, "y": 124 },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"type\"] == \"status\")\n  |> last()\n\n  \n"
    }
   ]
  }
 ]
}